language: node_js
node_js:
  - '24'
install:
  - bun install
script:
  - bun run build:storybook

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master
